// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using StrategyGame.Dal;

namespace StrategyGame.Dal.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.6-servicing-10079")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("StrategyGame.Model.Entities.Building", b =>
                {
                    b.Property<int>("BuildingId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("Grow_coral");

                    b.Property<int>("Grow_pop");

                    b.Property<string>("Name");

                    b.Property<int>("Price");

                    b.Property<int>("Space");

                    b.HasKey("BuildingId");

                    b.ToTable("Buildings");

                    b.HasData(
                        new
                        {
                            BuildingId = 1,
                            Grow_coral = 200,
                            Grow_pop = 50,
                            Name = "áramlásirányító",
                            Price = 1000,
                            Space = 0
                        },
                        new
                        {
                            BuildingId = 2,
                            Grow_coral = 0,
                            Grow_pop = 0,
                            Name = "zátonyvár",
                            Price = 1000,
                            Space = 200
                        });
                });

            modelBuilder.Entity("StrategyGame.Model.Entities.City", b =>
                {
                    b.Property<int>("CityId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("Coral");

                    b.Property<string>("Name");

                    b.Property<int>("Pearl");

                    b.Property<int>("Population");

                    b.Property<int>("Rank");

                    b.HasKey("CityId");

                    b.ToTable("Cities");
                });

            modelBuilder.Entity("StrategyGame.Model.Entities.CityArmy", b =>
                {
                    b.Property<int>("Id");

                    b.Property<int>("EnemyId");

                    b.Property<int>("Number");

                    b.HasKey("Id");

                    b.ToTable("CityArmy");
                });

            modelBuilder.Entity("StrategyGame.Model.Entities.CityBuilding", b =>
                {
                    b.Property<int>("CityId");

                    b.Property<int>("BuildingId");

                    b.Property<int>("Number");

                    b.Property<int>("RoundToFinish");

                    b.HasKey("CityId", "BuildingId");

                    b.HasIndex("BuildingId");

                    b.ToTable("CityBuilding");
                });

            modelBuilder.Entity("StrategyGame.Model.Entities.CityUnit", b =>
                {
                    b.Property<int>("Id");

                    b.Property<int>("Number");

                    b.Property<int?>("UnitId");

                    b.HasKey("Id");

                    b.HasIndex("UnitId");

                    b.ToTable("CityUnit");
                });

            modelBuilder.Entity("StrategyGame.Model.Entities.CityUpgrade", b =>
                {
                    b.Property<int>("Id");

                    b.Property<int>("RoundToFinish");

                    b.HasKey("Id");

                    b.ToTable("CityUpgrade");
                });

            modelBuilder.Entity("StrategyGame.Model.Entities.Rounds", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("ElapsedRounds");

                    b.HasKey("Id");

                    b.ToTable("Rounds");
                });

            modelBuilder.Entity("StrategyGame.Model.Entities.Unit", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("Attack");

                    b.Property<int>("Cost");

                    b.Property<int>("Defend");

                    b.Property<int>("Food");

                    b.Property<string>("Name");

                    b.Property<int>("Price");

                    b.HasKey("Id");

                    b.ToTable("Units");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Attack = 6,
                            Cost = 1,
                            Defend = 2,
                            Food = 1,
                            Name = "rohamfóka",
                            Price = 50
                        },
                        new
                        {
                            Id = 2,
                            Attack = 2,
                            Cost = 1,
                            Defend = 6,
                            Food = 1,
                            Name = "csatacsikó",
                            Price = 50
                        },
                        new
                        {
                            Id = 3,
                            Attack = 5,
                            Cost = 3,
                            Defend = 5,
                            Food = 2,
                            Name = "lézercápa",
                            Price = 100
                        });
                });

            modelBuilder.Entity("StrategyGame.Model.Entities.Upgrade", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("Attack");

                    b.Property<int>("Coral");

                    b.Property<int>("Defend");

                    b.Property<string>("Name");

                    b.Property<int>("Tax");

                    b.HasKey("Id");

                    b.ToTable("Upgrades");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Attack = 0,
                            Coral = 10,
                            Defend = 0,
                            Name = "iszaptraktor",
                            Tax = 0
                        },
                        new
                        {
                            Id = 2,
                            Attack = 0,
                            Coral = 15,
                            Defend = 0,
                            Name = "iszapkombájn",
                            Tax = 0
                        },
                        new
                        {
                            Id = 3,
                            Attack = 0,
                            Coral = 0,
                            Defend = 20,
                            Name = "korallfal",
                            Tax = 0
                        },
                        new
                        {
                            Id = 4,
                            Attack = 20,
                            Coral = 0,
                            Defend = 0,
                            Name = "szonárágyú",
                            Tax = 0
                        },
                        new
                        {
                            Id = 5,
                            Attack = 10,
                            Coral = 0,
                            Defend = 10,
                            Name = "vízalatti harcművészetek",
                            Tax = 0
                        },
                        new
                        {
                            Id = 6,
                            Attack = 0,
                            Coral = 0,
                            Defend = 0,
                            Name = "alkímia",
                            Tax = 30
                        });
                });

            modelBuilder.Entity("StrategyGame.Model.Entities.CityArmy", b =>
                {
                    b.HasOne("StrategyGame.Model.Entities.City", "City")
                        .WithMany("CityArmies")
                        .HasForeignKey("Id")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("StrategyGame.Model.Entities.Unit", "Unit")
                        .WithOne("Army")
                        .HasForeignKey("StrategyGame.Model.Entities.CityArmy", "Id")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("StrategyGame.Model.Entities.CityBuilding", b =>
                {
                    b.HasOne("StrategyGame.Model.Entities.Building", "Building")
                        .WithMany("CityBuildings")
                        .HasForeignKey("BuildingId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("StrategyGame.Model.Entities.City", "City")
                        .WithMany("CityBuildings")
                        .HasForeignKey("CityId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("StrategyGame.Model.Entities.CityUnit", b =>
                {
                    b.HasOne("StrategyGame.Model.Entities.City", "City")
                        .WithMany("CityUnits")
                        .HasForeignKey("Id")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("StrategyGame.Model.Entities.Unit", "Unit")
                        .WithMany()
                        .HasForeignKey("Id")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("StrategyGame.Model.Entities.Unit")
                        .WithMany("CityUnits")
                        .HasForeignKey("UnitId");
                });

            modelBuilder.Entity("StrategyGame.Model.Entities.CityUpgrade", b =>
                {
                    b.HasOne("StrategyGame.Model.Entities.City", "City")
                        .WithOne("Upgrade")
                        .HasForeignKey("StrategyGame.Model.Entities.CityUpgrade", "Id")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("StrategyGame.Model.Entities.Upgrade", "Upgrade")
                        .WithMany()
                        .HasForeignKey("Id")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
